### ISSUE TITLE
List of things to improve with pulsar

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/pulsar#100]
[TL;DR]
- [x] the pip version doesn't find the shell_plugins #109 
- [x] connection errors could be more obvious #103 
- [ ] parameters from job_conf.xml.sample_advanced apply to app.yml as well [missing doc]
- [x] ~~check_job_script_integrity should be configurable~~  check_job_script_integrity before headers https://github.com/galaxyproject/galaxy/pull/2146
- [ ] mention app.yml.sample prominently in docs, for people that start with pulsar-app installed through pip
- [x] GALAXY_SLOTS at 1, even though NCPUS=16 https://github.com/galaxyproject/galaxy/pull/2145
- [x]  problem starting up latest dev with galaxy.jobs.runners.pulsar:PulsarRESTJobRunner https://github.com/galaxyproject/galaxy/issues/2192

---

First of all, I'm amazed at how easy it was to submit pulsar jobs to our university's HPC cluster by ssh, which I didn't know existed yesterday at around this time! Seriously awesome @jmchilton .

The cluster is running PBS, and it is unlikely we can ever become submit hosts directly. There is a fronted server, to which researchers can login by ssh, transfer their data and submit jobs, so I thought Pulsar with a secure_shell plugin and torque are the right choice.

I first tried installing pulsar-app from pip, which gave me version 0.6.1
In the simplest config everything works fine, but once I change shell_plugin to SecureShell, I got this traceback when submitting jobs (server started with `pulsar`):

```
serving on http://127.0.0.1:8913
2016-04-12 14:59:30,536 DEBUG [pulsar.managers.base][[manager=_default_]-[action=preprocess]-[job=33]] job_id: 33 - Checking authorization of command_line [printenv > "/lustrework/vandenbeek/pulsar/pulsar-master/files/staging/33/outputs/dataset_33.dat"]
2016-04-12 14:59:30,537 ERROR [pulsar.managers.stateful][[manager=_default_]-[action=preprocess]-[job=33]] Failed job preprocess for 33:
Traceback (most recent call last):
  File "/Users/marius/.venv/lib/python2.7/site-packages/pulsar/managers/stateful.py", line 79, in do_preprocess
    self._proxied_manager.launch(job_id, *args, **kwargs)
  File "/Users/marius/.venv/lib/python2.7/site-packages/pulsar/managers/queued_cli.py", line 25, in launch
    shell, job_interface = self.__get_cli_plugins()
  File "/Users/marius/.venv/lib/python2.7/site-packages/pulsar/managers/queued_cli.py", line 49, in __get_cli_plugins
    return self.cli_interface.get_plugins(self.shell_params, self.job_params)
  File "/Users/marius/.venv/lib/python2.7/site-packages/pulsar/managers/util/cli/__init__.py", line 49, in get_plugins
    shell = self.get_shell_plugin(shell_params)
  File "/Users/marius/.venv/lib/python2.7/site-packages/pulsar/managers/util/cli/__init__.py", line 55, in get_shell_plugin
    shell = self.cli_shells[shell_plugin](**shell_params)
KeyError: 'SecureShell'
```

The current master branch had the same problem..
Then I tried changing into the root directory of the pulsar master branch, and used
paster serve server.ini, and this error went away. So I guess this is an import/path issue.

Then I had problems connecting by ssh, but the error message wasn't very helpful.

```
2016-04-12 15:09:00,613 WARNI [pulsar.managers.queued_cli][[manager=_default_]-[action=preprocess]-[job=36]] Failed to submit job - command was qsub /Users/marius/pulsar/pulsar/files/staging/36/command.sh
2016-04-12 15:09:00,614 ERROR [pulsar.managers.stateful][[manager=_default_]-[action=preprocess]-[job=36]] Failed job preprocess for 36:
Traceback (most recent call last):
  File "/Users/marius/pulsar/pulsar/pulsar/managers/stateful.py", line 78, in do_preprocess
    self._proxied_manager.launch(job_id, *args, **kwargs)
  File "/Users/marius/pulsar/pulsar/pulsar/managers/queued_cli.py", line 39, in launch
    raise Exception("Failed to submit job")
Exception: Failed to submit job
```

Turns out I hadn't added the ECSDA host key to the known_hosts (I typically just ignore them on my dev machine).
I guess when establishing the connection, and there is an error, the error could be returned.

Next thing is that it wasn't very obvious that you can simply translate the resource requests from the job_conf.xml into yaml format. I can add a PR to the docs for this

Then I'm not sure how this part is supposed to work, but for some reason I can't submit jobs when this is present:

```
# The following block can be used by the job system
# to ensure this script is runnable before actually attempting
# to run it.
if [ -n "$ABC_TEST_JOB_SCRIPT_INTEGRITY_XYZ" ]; then
    exit 42
fi
```

I have a quick'n-dirty PR ready to make this configurable.
So now I'm successfully submitting ( have I mentioned how awesome that is?!!!), 
let's see how this works out in practice.

**Comment by mvdbeek** [comment]
Tow more things I forgot:
With the latest galaxy dev I get an import error for pulsar core, switching to release_16.01 helped with that.
And GALAXY_SLOTS=1 even though I requested 16 CPUs.
Thats the output of `printenv`:
```
LESSKEY=/etc/lesskey.bin
MODULE_VERSION_STACK=3.1.6
MANPATH=/usr/lib64/mpi/gcc/openmpi/share/man:/usr/local/man:/usr/share/man:/opt/c3/man:/opt/gnome/share/man:/usr/share/man:/usr/local/man:/opt/pbs/default/man:/opt/sgi/share/man
INFODIR=/usr/local/info:/usr/share/info:/usr/info
NNTPSERVER=news
HOSTNAME=r1i0n21
XKEYSYMDB=/usr/share/X11/XKeysymDB
GNOME2_PATH=/usr/local:/opt/gnome:/usr
_MODULESBEGINENV_=/home/vandenbeek/.modulesbeginenv
SHELL=/bin/bash
HOST=r1i0n21
HISTSIZE=1000
PROFILEREAD=true
PBS_JOBNAME=pulsar_70
TMPDIR=/lustrework/pbs.214246.mesu0
PBS_ENVIRONMENT=PBS_BATCH
MORE=-sl
OLDPWD=/home/vandenbeek/pbs.214246.mesu0.x8z
PBS_O_WORKDIR=/home/vandenbeek
NCPUS=16
GALAXY_SLOTS_CONFIGURED=1
USER=vandenbeek
PBS_TASKNUM=1
JRE_HOME=/usr/lib64/jvm/jre
LD_LIBRARY_PATH=/usr/lib64/mpi/gcc/openmpi/lib64
LS_COLORS=
PBS_O_HOME=/home/vandenbeek
XNLSPATH=/usr/X11R6/lib/X11/nls
ENV=/etc/bash.bashrc
HOSTTYPE=x86_64
OSCAR_HOME=/opt/oscar
PBS_MOMPORT=15003
FROM_HEADER=
PAGER=less
CSHEDIT=emacs
PBS_O_QUEUE=entry
XDG_CONFIG_DIRS=/etc/xdg
MINICOM=-c on
PATH=/home/vandenbeek/miniconda2/bin:/opt/sgi/sbin:/opt/sgi/bin:/usr/lib64/mpi/gcc/openmpi/bin:/home/vandenbeek/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib64/jvm/jre/bin:/opt/c3/bin:/opt/ibutils/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/opt/pbs/default/bin:/opt/pbs/default/sbin:.
PBS_O_LOGNAME=vandenbeek
MAIL=/var/spool/mail/vandenbeek
MODULE_VERSION=3.1.6
CPU=x86_64
PBS_JOBCOOKIE=000000006414CDDA000000005EF96F86
JAVA_BINDIR=/usr/lib64/jvm/jre/bin
PWD=/lustrework/vandenbeek/staging/70/working
INPUTRC=/home/vandenbeek/.inputrc
GALAXY_SLOTS=1
JAVA_HOME=/usr/lib64/jvm/jre
PBS_NODENUM=0
LANG=en_US.UTF-8
MODULEPATH=/usr/share/modules:/usr/share/modules/modulefiles:/opt/dev/modulefiles
PYTHONSTARTUP=/etc/pythonstart
TZ=US/Central
PBS_JOBDIR=/home/vandenbeek/pbs.214246.mesu0.x8z
LOADEDMODULES=
PBS_O_SHELL=/bin/bash
C3_RSH=ssh -oConnectTimeout=10 -oForwardX11=no
PBS_JOBID=214246.mesu0
ENVIRONMENT=BATCH
HOME=/home/vandenbeek
SHLVL=2
QT_SYSTEM_DIR=/usr/share/desktop-data
OSTYPE=linux
LESS_ADVANCED_PREPROCESSOR=no
LANGUAGE=en_US.UTF-8
PBS_O_HOST=mesu0.dsi.upmc.fr
XCURSOR_THEME=crystalwhite
LS_OPTIONS=-N --color=none -T 0
WINDOWMANAGER=
LOGNAME=vandenbeek
MACHTYPE=x86_64-suse-linux
LESS=-M -I
G_FILENAME_ENCODING=@locale,UTF-8,ISO-8859-15,CP1252
CVS_RSH=ssh
PBS_QUEUE=f96c
ACLOCAL_FLAGS=-I /opt/gnome/share/aclocal
XDG_DATA_DIRS=/usr/share:/opt/gnome/share
MODULESHOME=/usr/share/modules
PBS_O_MAIL=/var/mail/vandenbeek
OMP_NUM_THREADS=16
LESSOPEN=lessopen.sh %s
PKG_CONFIG_PATH=/opt/gnome/lib64/pkgconfig:/opt/gnome/share/pkgconfig
INFOPATH=/usr/local/info:/usr/share/info:/usr/info:/opt/gnome/share/info
PBS_O_SYSTEM=Linux
LESSCLOSE=lessclose.sh %s %s
PBS_NODEFILE=/var/spool/PBS/aux/214246.mesu0
G_BROKEN_FILENAMES=1
PBS_O_PATH=/home/vandenbeek/miniconda2/bin:/home/vandenbeek/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/sgi/sgimc/bin:/opt/pbs/default/bin:/opt/pbs/default/sbin:/opt/pbs/default/bin:/opt/pbs/default/sbin:/opt/intel/flexlm:/opt/dev/intel/eclipse
COLORTERM=1
JAVA_ROOT=/usr/lib64/jvm/jre
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
_=/usr/bin/printenv
```
